@startuml
interface IResourceGroupCollection {
    Ready : bool <<get>>
    TotalCount : int <<get>>
    ReadyCount : int <<get>>
    TotalLength : long <<get>>
    TotalCompressedLength : long <<get>>
    ReadyLength : long <<get>>
    ReadyCompressedLength : long <<get>>
    Progress : float <<get>>
    GetResourceGroups() : IResourceGroup[]
    GetResourceNames() : string[]
    GetResourceNames(results:List<string>) : void
}
@enduml
