@startuml
class LoadResourceAgentHelperReadFileCompleteEventArgs <<sealed>> {
    + LoadResourceAgentHelperReadFileCompleteEventArgs()
    + Resource : object <<get>>
    + {static} Create(resource:object) : LoadResourceAgentHelperReadFileCompleteEventArgs
    + <<override>> Clear() : void
}
GameFrameworkEventArgs <|-- LoadResourceAgentHelperReadFileCompleteEventArgs
@enduml
