@startuml
class PackageVersionList <<struct>> {
}
class ResourceGroup <<struct>> {
    - {static} <<readonly>> EmptyIntArray : int[]
    - <<readonly>> m_Name : string
    - <<readonly>> m_ResourceIndexes : int[]
    + ResourceGroup(name:string, resourceIndexes:int[])
    + Name : string <<get>>
    + GetResourceIndexes() : int[]
}
PackageVersionList +-- ResourceGroup
@enduml
