@startuml
class ResourcePackVersionListSerializer <<sealed>> {
    - {static} <<readonly>> Header : byte[]
    + ResourcePackVersionListSerializer()
    # <<override>> GetHeader() : byte[]
}
"GameFrameworkSerializer`1" "<ResourcePackVersionList>" <|-- ResourcePackVersionListSerializer
@enduml
