@startuml
class ResourceManager <<sealed>> <<partial>> {
}
enum LoadType {
    LoadFromFile= 0,
    LoadFromMemory,
    LoadFromMemoryAndQuickDecrypt,
    LoadFromMemoryAndDecrypt,
    LoadFromBinary,
    LoadFromBinaryAndQuickDecrypt,
    LoadFromBinaryAndDecrypt,
}
GameFrameworkModule <|-- ResourceManager
IResourceManager <|-- ResourceManager
ResourceManager +-- LoadType
@enduml
