@startuml
class ResourceUpdateAllCompleteEventArgs <<sealed>> {
    + ResourceUpdateAllCompleteEventArgs()
    + {static} Create() : ResourceUpdateAllCompleteEventArgs
    + <<override>> Clear() : void
}
GameFrameworkEventArgs <|-- ResourceUpdateAllCompleteEventArgs
@enduml
