@startuml
class UpdatableVersionList <<struct>> {
}
class Asset <<struct>> {
    - {static} <<readonly>> EmptyIntArray : int[]
    - <<readonly>> m_Name : string
    - <<readonly>> m_DependencyAssetIndexes : int[]
    + Asset(name:string, dependencyAssetIndexes:int[])
    + Name : string <<get>>
    + GetDependencyAssetIndexes() : int[]
}
UpdatableVersionList +-- Asset
@enduml
