@startuml
class ResetSoundAgentEventArgs <<sealed>> {
    + ResetSoundAgentEventArgs()
    + {static} Create() : ResetSoundAgentEventArgs
    + <<override>> Clear() : void
}
GameFrameworkEventArgs <|-- ResetSoundAgentEventArgs
@enduml
