@startuml
enum NetworkErrorCode {
    Unknown= 0,
    AddressFamilyError,
    SocketError,
    ConnectError,
    SendError,
    ReceiveError,
    SerializeError,
    DeserializePacketHeaderError,
    DeserializePacketError,
}
@enduml
