@startuml
interface IDataNode {
    Name : string <<get>>
    FullName : string <<get>>
    Parent : IDataNode <<get>>
    ChildCount : int <<get>>
    GetData() : T
    GetData() : Variable
    SetData(data:T) : void
    SetData(data:Variable) : void
    HasChild(index:int) : bool
    HasChild(name:string) : bool
    GetChild(index:int) : IDataNode
    GetChild(name:string) : IDataNode
    GetOrAddChild(name:string) : IDataNode
    GetAllChild() : IDataNode[]
    GetAllChild(results:List<IDataNode>) : void
    RemoveChild(index:int) : void
    RemoveChild(name:string) : void
    Clear() : void
    ToString() : string
    ToDataString() : string
}
@enduml
