@startuml
abstract class GameFrameworkEventArgs {
    + GameFrameworkEventArgs()
    + {abstract} Clear() : void
}
EventArgs <|-- GameFrameworkEventArgs
IReference <|-- GameFrameworkEventArgs
@enduml
