@startuml
interface IEventManager {
    EventHandlerCount : int <<get>>
    EventCount : int <<get>>
    Count(id:int) : int
    Check(id:int, handler:EventHandler<GameEventArgs>) : bool
    Subscribe(id:int, handler:EventHandler<GameEventArgs>) : void
    Unsubscribe(id:int, handler:EventHandler<GameEventArgs>) : void
    SetDefaultHandler(handler:EventHandler<GameEventArgs>) : void
    Fire(sender:object, e:GameEventArgs) : void
    FireNow(sender:object, e:GameEventArgs) : void
}
@enduml
