@startuml
skinparam dpi 800
scale 80000 width
scale 2200 height
!include .\\Base\GameFrameworkAction.puml
!include .\\Base\GameFrameworkEntry.puml
!include .\\Base\GameFrameworkEventArgs.puml
!include .\\Base\GameFrameworkException.puml
!include .\\Base\GameFrameworkFunc.puml
!include .\\Base\GameFrameworkLinkedList.puml
!include .\\Base\GameFrameworkLinkedListRange.puml
!include .\\Base\GameFrameworkModule.puml
!include .\\Base\GameFrameworkMultiDictionary.puml
!include .\\Base\GameFrameworkSerializer.puml
!include .\\Config\ConfigManager.ConfigData.puml
!include .\\Config\ConfigManager.puml
!include .\\Config\IConfigHelper.puml
!include .\\Config\IConfigManager.puml
!include .\\DataNode\DataNodeManager.puml
!include .\\DataNode\DataNodeManager.DataNode.puml
!include .\\DataNode\IDataNode.puml
!include .\\DataNode\IDataNodeManager.puml
!include .\\DataTable\DataTableBase.puml
!include .\\DataTable\DataTableManager.puml
!include .\\DataTable\DataTableManager.DataTable.puml
!include .\\DataTable\IDataRow.puml
!include .\\DataTable\IDataTable.puml
!include .\\DataTable\IDataTableHelper.puml
!include .\\DataTable\IDataTableManager.puml
!include .\\Debugger\DebuggerManager.puml
!include .\\Debugger\DebuggerManager.DebuggerWindowGroup.puml
!include .\\Debugger\IDebuggerManager.puml
!include .\\Debugger\IDebuggerWindow.puml
!include .\\Debugger\IDebuggerWindowGroup.puml
!include .\\Download\Constant.puml
!include .\\Download\DownloadAgentHelperCompleteEventArgs.puml
!include .\\Download\DownloadAgentHelperErrorEventArgs.puml
!include .\\Download\DownloadAgentHelperUpdateBytesEventArgs.puml
!include .\\Download\DownloadAgentHelperUpdateLengthEventArgs.puml
!include .\\Download\DownloadFailureEventArgs.puml
!include .\\Download\DownloadManager.puml
!include .\\Download\DownloadManager.DownloadAgent.puml
!include .\\Download\DownloadManager.DownloadCounter.puml
!include .\\Download\DownloadManager.DownloadCounter.DownloadCounterNode.puml
!include .\\Download\DownloadManager.DownloadTask.puml
!include .\\Download\DownloadManager.DownloadTaskStatus.puml
!include .\\Download\DownloadStartEventArgs.puml
!include .\\Download\DownloadSuccessEventArgs.puml
!include .\\Download\DownloadUpdateEventArgs.puml
!include .\\Download\IDownloadAgentHelper.puml
!include .\\Download\IDownloadManager.puml
!include .\\Entity\EntityManager.puml
!include .\\Entity\EntityManager.EntityGroup.puml
!include .\\Entity\EntityManager.EntityInfo.puml
!include .\\Entity\EntityManager.EntityInstanceObject.puml
!include .\\Entity\EntityManager.EntityStatus.puml
!include .\\Entity\EntityManager.ShowEntityInfo.puml
!include .\\Entity\HideEntityCompleteEventArgs.puml
!include .\\Entity\IEntity.puml
!include .\\Entity\IEntityGroup.puml
!include .\\Entity\IEntityGroupHelper.puml
!include .\\Entity\IEntityHelper.puml
!include .\\Entity\IEntityManager.puml
!include .\\Entity\ShowEntityDependencyAssetEventArgs.puml
!include .\\Entity\ShowEntityFailureEventArgs.puml
!include .\\Entity\ShowEntitySuccessEventArgs.puml
!include .\\Entity\ShowEntityUpdateEventArgs.puml
!include .\\Event\EventManager.puml
!include .\\Event\GameEventArgs.puml
!include .\\Event\IEventManager.puml
!include .\\FileSystem\CommonFileSystemStream.puml
!include .\\FileSystem\FileInfo.puml
!include .\\FileSystem\FileSystem.BlockData.puml
!include .\\FileSystem\FileSystem.puml
!include .\\FileSystem\FileSystem.HeaderData.puml
!include .\\FileSystem\FileSystem.StringData.puml
!include .\\FileSystem\FileSystemAccess.puml
!include .\\FileSystem\FileSystemManager.puml
!include .\\FileSystem\FileSystemStream.puml
!include .\\FileSystem\IFileSystem.puml
!include .\\FileSystem\IFileSystemHelper.puml
!include .\\FileSystem\IFileSystemManager.puml
!include .\\Fsm\Fsm.puml
!include .\\Fsm\FsmBase.puml
!include .\\Fsm\FsmManager.puml
!include .\\Fsm\FsmState.puml
!include .\\Fsm\IFsm.puml
!include .\\Fsm\IFsmManager.puml
!include .\\Localization\ILocalizationHelper.puml
!include .\\Localization\ILocalizationManager.puml
!include .\\Localization\Language.puml
!include .\\Localization\LocalizationManager.puml
!include .\\Network\AddressFamily.puml
!include .\\Network\INetworkChannel.puml
!include .\\Network\INetworkChannelHelper.puml
!include .\\Network\INetworkManager.puml
!include .\\Network\IPacketHandler.puml
!include .\\Network\IPacketHeader.puml
!include .\\Network\NetworkClosedEventArgs.puml
!include .\\Network\NetworkConnectedEventArgs.puml
!include .\\Network\NetworkCustomErrorEventArgs.puml
!include .\\Network\NetworkErrorCode.puml
!include .\\Network\NetworkErrorEventArgs.puml
!include .\\Network\NetworkManager.ConnectState.puml
!include .\\Network\NetworkManager.puml
!include .\\Network\NetworkManager.HeartBeatState.puml
!include .\\Network\NetworkManager.NetworkChannelBase.puml
!include .\\Network\NetworkManager.ReceiveState.puml
!include .\\Network\NetworkManager.SendState.puml
!include .\\Network\NetworkManager.TcpNetworkChannel.puml
!include .\\Network\NetworkManager.TcpWithSyncReceiveNetworkChannel.puml
!include .\\Network\NetworkMissHeartBeatEventArgs.puml
!include .\\Network\Packet.puml
!include .\\Network\ServiceType.puml
!include .\\ObjectPool\IObjectPool.puml
!include .\\ObjectPool\IObjectPoolManager.puml
!include .\\ObjectPool\ObjectBase.puml
!include .\\ObjectPool\ObjectInfo.puml
!include .\\ObjectPool\ObjectPoolBase.puml
!include .\\ObjectPool\ObjectPoolManager.puml
!include .\\ObjectPool\ObjectPoolManager.Object.puml
!include .\\ObjectPool\ObjectPoolManager.ObjectPool.puml
!include .\\ObjectPool\ReleaseObjectFilterCallback.puml
!include .\\Procedure\IProcedureManager.puml
!include .\\Procedure\ProcedureBase.puml
!include .\\Procedure\ProcedureManager.puml
!include .\\Properties\AssemblyInfo.puml
!include .\\Resource\ApplyResourcesCompleteCallback.puml
!include .\\Resource\CheckResourcesCompleteCallback.puml
!include .\\Resource\CheckVersionListResult.puml
!include .\\Resource\Constant.puml
!include .\\Resource\DecryptResourceCallback.puml
!include .\\Resource\HasAssetResult.puml
!include .\\Resource\ILoadResourceAgentHelper.puml
!include .\\Resource\InitResourcesCompleteCallback.puml
!include .\\Resource\IResourceGroup.puml
!include .\\Resource\IResourceGroupCollection.puml
!include .\\Resource\IResourceHelper.puml
!include .\\Resource\IResourceManager.puml
!include .\\Resource\LoadAssetCallbacks.puml
!include .\\Resource\LoadAssetDependencyAssetCallback.puml
!include .\\Resource\LoadAssetFailureCallback.puml
!include .\\Resource\LoadAssetSuccessCallback.puml
!include .\\Resource\LoadAssetUpdateCallback.puml
!include .\\Resource\LoadBinaryCallbacks.puml
!include .\\Resource\LoadBinaryFailureCallback.puml
!include .\\Resource\LoadBinarySuccessCallback.puml
!include .\\Resource\LoadBytesCallbacks.puml
!include .\\Resource\LoadBytesFailureCallback.puml
!include .\\Resource\LoadBytesSuccessCallback.puml
!include .\\Resource\LoadResourceAgentHelperErrorEventArgs.puml
!include .\\Resource\LoadResourceAgentHelperLoadCompleteEventArgs.puml
!include .\\Resource\LoadResourceAgentHelperParseBytesCompleteEventArgs.puml
!include .\\Resource\LoadResourceAgentHelperReadBytesCompleteEventArgs.puml
!include .\\Resource\LoadResourceAgentHelperReadFileCompleteEventArgs.puml
!include .\\Resource\LoadResourceAgentHelperUpdateEventArgs.puml
!include .\\Resource\LoadResourceProgress.puml
!include .\\Resource\LoadResourceStatus.puml
!include .\\Resource\LoadSceneCallbacks.puml
!include .\\Resource\LoadSceneDependencyAssetCallback.puml
!include .\\Resource\LoadSceneFailureCallback.puml
!include .\\Resource\LoadSceneSuccessCallback.puml
!include .\\Resource\LoadSceneUpdateCallback.puml
!include .\\Resource\LocalVersionList.puml
!include .\\Resource\LocalVersionList.FileSystem.puml
!include .\\Resource\LocalVersionList.Resource.puml
!include .\\Resource\PackageVersionList.Asset.puml
!include .\\Resource\PackageVersionList.puml
!include .\\Resource\PackageVersionList.FileSystem.puml
!include .\\Resource\PackageVersionList.Resource.puml
!include .\\Resource\PackageVersionList.ResourceGroup.puml
!include .\\Resource\PackageVersionListSerializer.puml
!include .\\Resource\ReadOnlyVersionListSerializer.puml
!include .\\Resource\ReadWriteVersionListSerializer.puml
!include .\\Resource\ResourceApplyFailureEventArgs.puml
!include .\\Resource\ResourceApplyStartEventArgs.puml
!include .\\Resource\ResourceApplySuccessEventArgs.puml
!include .\\Resource\ResourceManager.AssetInfo.puml
!include .\\Resource\ResourceManager.puml
!include .\\Resource\ResourceManager.LoadType.puml
!include .\\Resource\ResourceManager.ReadWriteResourceInfo.puml
!include .\\Resource\ResourceManager.ResourceChecker.CheckInfo.CheckStatus.puml
!include .\\Resource\ResourceManager.ResourceChecker.CheckInfo.puml
!include .\\Resource\ResourceManager.ResourceChecker.CheckInfo.LocalVersionInfo.puml
!include .\\Resource\ResourceManager.ResourceChecker.CheckInfo.RemoteVersionInfo.puml
!include .\\Resource\ResourceManager.ResourceChecker.puml
!include .\\Resource\ResourceManager.ResourceGroup.puml
!include .\\Resource\ResourceManager.ResourceGroupCollection.puml
!include .\\Resource\ResourceManager.ResourceInfo.puml
!include .\\Resource\ResourceManager.ResourceIniter.puml
!include .\\Resource\ResourceManager.ResourceLoader.AssetObject.puml
!include .\\Resource\ResourceManager.ResourceLoader.puml
!include .\\Resource\ResourceManager.ResourceLoader.LoadAssetTask.puml
!include .\\Resource\ResourceManager.ResourceLoader.LoadBinaryInfo.puml
!include .\\Resource\ResourceManager.ResourceLoader.LoadDependencyAssetTask.puml
!include .\\Resource\ResourceManager.ResourceLoader.LoadResourceAgent.puml
!include .\\Resource\ResourceManager.ResourceLoader.LoadResourceTaskBase.puml
!include .\\Resource\ResourceManager.ResourceLoader.LoadSceneTask.puml
!include .\\Resource\ResourceManager.ResourceLoader.ResourceObject.puml
!include .\\Resource\ResourceManager.ResourceName.puml
!include .\\Resource\ResourceManager.ResourceNameComparer.puml
!include .\\Resource\ResourceManager.ResourceUpdater.ApplyInfo.puml
!include .\\Resource\ResourceManager.ResourceUpdater.puml
!include .\\Resource\ResourceManager.ResourceUpdater.UpdateInfo.puml
!include .\\Resource\ResourceManager.ResourceVerifier.puml
!include .\\Resource\ResourceManager.ResourceVerifier.VerifyInfo.puml
!include .\\Resource\ResourceManager.VersionListProcessor.puml
!include .\\Resource\ResourceMode.puml
!include .\\Resource\ResourcePackVersionList.puml
!include .\\Resource\ResourcePackVersionList.Resource.puml
!include .\\Resource\ResourcePackVersionListSerializer.puml
!include .\\Resource\ResourceUpdateAllCompleteEventArgs.puml
!include .\\Resource\ResourceUpdateChangedEventArgs.puml
!include .\\Resource\ResourceUpdateFailureEventArgs.puml
!include .\\Resource\ResourceUpdateStartEventArgs.puml
!include .\\Resource\ResourceUpdateSuccessEventArgs.puml
!include .\\Resource\ResourceVerifyFailureEventArgs.puml
!include .\\Resource\ResourceVerifyStartEventArgs.puml
!include .\\Resource\ResourceVerifySuccessEventArgs.puml
!include .\\Resource\UnloadSceneCallbacks.puml
!include .\\Resource\UnloadSceneFailureCallback.puml
!include .\\Resource\UnloadSceneSuccessCallback.puml
!include .\\Resource\UpdatableVersionList.Asset.puml
!include .\\Resource\UpdatableVersionList.puml
!include .\\Resource\UpdatableVersionList.FileSystem.puml
!include .\\Resource\UpdatableVersionList.Resource.puml
!include .\\Resource\UpdatableVersionList.ResourceGroup.puml
!include .\\Resource\UpdatableVersionListSerializer.puml
!include .\\Resource\UpdateResourcesCompleteCallback.puml
!include .\\Resource\UpdateVersionListCallbacks.puml
!include .\\Resource\UpdateVersionListFailureCallback.puml
!include .\\Resource\UpdateVersionListSuccessCallback.puml
!include .\\Resource\VerifyResourcesCompleteCallback.puml
!include .\\Scene\ISceneManager.puml
!include .\\Scene\LoadSceneDependencyAssetEventArgs.puml
!include .\\Scene\LoadSceneFailureEventArgs.puml
!include .\\Scene\LoadSceneSuccessEventArgs.puml
!include .\\Scene\LoadSceneUpdateEventArgs.puml
!include .\\Scene\SceneManager.puml
!include .\\Scene\UnloadSceneFailureEventArgs.puml
!include .\\Scene\UnloadSceneSuccessEventArgs.puml
!include .\\Setting\ISettingHelper.puml
!include .\\Setting\ISettingManager.puml
!include .\\Setting\SettingManager.puml
!include .\\Sound\Constant.puml
!include .\\Sound\ISoundAgent.puml
!include .\\Sound\ISoundAgentHelper.puml
!include .\\Sound\ISoundGroup.puml
!include .\\Sound\ISoundGroupHelper.puml
!include .\\Sound\ISoundHelper.puml
!include .\\Sound\ISoundManager.puml
!include .\\Sound\PlaySoundDependencyAssetEventArgs.puml
!include .\\Sound\PlaySoundErrorCode.puml
!include .\\Sound\PlaySoundFailureEventArgs.puml
!include .\\Sound\PlaySoundParams.puml
!include .\\Sound\PlaySoundSuccessEventArgs.puml
!include .\\Sound\PlaySoundUpdateEventArgs.puml
!include .\\Sound\ResetSoundAgentEventArgs.puml
!include .\\Sound\SoundManager.puml
!include .\\Sound\SoundManager.PlaySoundInfo.puml
!include .\\Sound\SoundManager.SoundAgent.puml
!include .\\Sound\SoundManager.SoundGroup.puml
!include .\\UI\CloseUIFormCompleteEventArgs.puml
!include .\\UI\IUIForm.puml
!include .\\UI\IUIFormHelper.puml
!include .\\UI\IUIGroup.puml
!include .\\UI\IUIGroupHelper.puml
!include .\\UI\IUIManager.puml
!include .\\UI\OpenUIFormDependencyAssetEventArgs.puml
!include .\\UI\OpenUIFormFailureEventArgs.puml
!include .\\UI\OpenUIFormSuccessEventArgs.puml
!include .\\UI\OpenUIFormUpdateEventArgs.puml
!include .\\UI\UIManager.puml
!include .\\UI\UIManager.OpenUIFormInfo.puml
!include .\\UI\UIManager.UIFormInstanceObject.puml
!include .\\UI\UIManager.UIGroup.puml
!include .\\UI\UIManager.UIGroup.UIFormInfo.puml
!include .\\Utility\Utility.Assembly.puml
!include .\\Utility\Utility.Compression.puml
!include .\\Utility\Utility.Compression.ICompressionHelper.puml
!include .\\Utility\Utility.Converter.puml
!include .\\Utility\Utility.puml
!include .\\Utility\Utility.Encryption.puml
!include .\\Utility\Utility.Json.puml
!include .\\Utility\Utility.Json.IJsonHelper.puml
!include .\\Utility\Utility.Marshal.puml
!include .\\Utility\Utility.Path.puml
!include .\\Utility\Utility.Random.puml
!include .\\Utility\Utility.Text.puml
!include .\\Utility\Utility.Text.ITextHelper.puml
!include .\\Utility\Utility.Verifier.Crc32.puml
!include .\\Utility\Utility.Verifier.puml
!include .\\WebRequest\Constant.puml
!include .\\WebRequest\IWebRequestAgentHelper.puml
!include .\\WebRequest\IWebRequestManager.puml
!include .\\WebRequest\WebRequestAgentHelperCompleteEventArgs.puml
!include .\\WebRequest\WebRequestAgentHelperErrorEventArgs.puml
!include .\\WebRequest\WebRequestFailureEventArgs.puml
!include .\\WebRequest\WebRequestManager.puml
!include .\\WebRequest\WebRequestManager.WebRequestAgent.puml
!include .\\WebRequest\WebRequestManager.WebRequestTask.puml
!include .\\WebRequest\WebRequestManager.WebRequestTaskStatus.puml
!include .\\WebRequest\WebRequestStartEventArgs.puml
!include .\\WebRequest\WebRequestSuccessEventArgs.puml
!include .\\Base\DataProvider\DataProvider.puml
!include .\\Base\DataProvider\DataProviderCreator.puml
!include .\\Base\DataProvider\IDataProvider.puml
!include .\\Base\DataProvider\IDataProviderHelper.puml
!include .\\Base\DataProvider\ReadDataDependencyAssetEventArgs.puml
!include .\\Base\DataProvider\ReadDataFailureEventArgs.puml
!include .\\Base\DataProvider\ReadDataSuccessEventArgs.puml
!include .\\Base\DataProvider\ReadDataUpdateEventArgs.puml
!include .\\Base\DataStruct\TypeNamePair.puml
!include .\\Base\EventPool\BaseEventArgs.puml
!include .\\Base\EventPool\EventPool.puml
!include .\\Base\EventPool\EventPool.Event.puml
!include .\\Base\EventPool\EventPoolMode.puml
!include .\\Base\Log\GameFrameworkLog.puml
!include .\\Base\Log\GameFrameworkLog.ILogHelper.puml
!include .\\Base\Log\GameFrameworkLogLevel.puml
!include .\\Base\ReferencePool\IReference.puml
!include .\\Base\ReferencePool\ReferencePool.puml
!include .\\Base\ReferencePool\ReferencePool.ReferenceCollection.puml
!include .\\Base\ReferencePool\ReferencePoolInfo.puml
!include .\\Base\TaskPool\ITaskAgent.puml
!include .\\Base\TaskPool\StartTaskStatus.puml
!include .\\Base\TaskPool\TaskBase.puml
!include .\\Base\TaskPool\TaskInfo.puml
!include .\\Base\TaskPool\TaskPool.puml
!include .\\Base\TaskPool\TaskStatus.puml
!include .\\Base\Variable\GenericVariable.puml
!include .\\Base\Variable\Variable.puml
!include .\\Base\Version\Version.puml
!include .\\Base\Version\Version.IVersionHelper.puml
@enduml
